### ISSUE TITLE
Problem running your code in Omnet 6.0

### ISSUE THREAD

**Issue by relespi** [gianlucagrassog/WSNOMNeT#1]
Hi, I try to modify  this code in order to run it in Omnet 6.0. Right now it ready to run but i faced some problems, for example, when starts running the omnet asked me for InterfaceTableModule. So, i checked that in the code, there is one part of the Node that is assigned something from =default(abspaht(.interfaceTable)). Could you please help what do i need to do in order to run the code because if a put "" for this entry the code stops at event 2 and i am getting the following message. 

Tag 'inet::PacketProtocolTag' is present -- in module (inet::Aloha_Ieee802154Mac) TestNet.source[4].wlan.mac (id=85), at t=0.184210466454s, event #2

and stops.

**Comment by gianlucagrassog** [comment]
I used omnetpp 5.6.2 with inet framework and everything worked fine.
You can try to add an extra * 
so
`**.interfaceTableModule = default(absPath(".interfaceTable"));`
instead of
`*.interfaceTableModule = default(absPath(".interfaceTable"));`

**Comment by relespi** [comment]
Now it does not ask me for the interfaceTableModule but still the same error 

Tag 'inet::PacketProtocolTag' is present -- in module (inet::Aloha_Ieee802154Mac) TestNet.source[4].wlan.mac (id=85), at t=0.184210466454s, event #2

I will try to run in Omnet 5.6.2 and what version of inet did you use?

**Comment by gianlucagrassog** [comment]
Maybe is Omnet 6.0 that cause the error, it is still a preview.
Try with **INET-4.2.3 (April 22, 2021) - Stable** and **Omnet 5.6.2**

**Comment by relespi** [comment]
Thanks
